### ISSUE TITLE
how to properly package the app

### ISSUE THREAD

**Issue by anserwaseem** [tuliocll/electron-react-sqlite-todo#3]
## Issue
Are there any other steps to [package](https://electron-react-boilerplate.js.org/docs/packaging) the app besides this:
`yarn package`

### Folder structure after packaging
<img width="437" alt="image" src="https://github.com/tuliocll/electron-react-sqlite-todo/assets/32386713/180de6ac-3c72-419f-8b14-0ba33b0e854d">

### Error in packaged app
<img width="1037" alt="image" src="https://github.com/tuliocll/electron-react-sqlite-todo/assets/32386713/6aa56075-09ae-44ee-861e-5ee09c6992fd">

**Comment by tuliocll** [comment]
On the post/project I didn't cover the package/release part, just the development.
This error is because you need to include the `database.db` file in your package and unpack it before use.
Check it on the boilerplate docs [here](https://electron-react-boilerplate.js.org/docs/adding-assets) and about the unpack (asarUnpack) option [here](https://www.electron.build/configuration/configuration.html#overridable-per-platform-options).

I created a [new commit to add this to the project too](https://github.com/tuliocll/electron-react-sqlite-todo/commit/733df816df2e11dbbf17c36bbcfdb57c76c58f63).

**Comment by anserwaseem** [comment]
Thank you, `database.db` is now included in packaged app but I still get that popup "Error registering user" with false being logged in console, 
Additionally, when I try to log in, it throws this error (tried packaging the app on Mac M2 Max and Windows 11; seeing same issues on both systems)

<img width="1027" alt="image" src="https://github.com/tuliocll/electron-react-sqlite-todo/assets/32386713/1cf8c6b5-b425-455b-a504-f1336a91b570">

Am I missing something here?

**Comment by tuliocll** [comment]
> Thank you, `database.db` is now included in packaged app but I still get that popup "Error registering user" with false being logged in console, Additionally, when I try to log in, it throws this error (tried packaging the app on Mac M2 Max and Windows 11; seeing same issues on both systems)
> 
> <img alt="image" width="1027" src="https://user-images.githubusercontent.com/32386713/271847643-1cf8c6b5-b425-455b-a504-f1336a91b570.png">
> Am I missing something here?

Are you trying with the new changes? Looks like the database file was not found. It`s a packaged executable or are you running in development?

**Comment by anserwaseem** [comment]
> Are you trying with the new changes? Looks like the database file was not found. It`s a packaged executable or are you running in development?

Yes, im trying with your latest commit, running packaged executable using this [command](https://electron-react-boilerplate.js.org/docs/packaging#debugging-production-builds)

<img width="1348" alt="image" src="https://github.com/tuliocll/electron-react-sqlite-todo/assets/32386713/a5ae3d4d-98d9-4763-a17f-affa35556cf0">

**Comment by tuliocll** [comment]
> > Are you trying with the new changes? Looks like the database file was not found. It`s a packaged executable or are you running in development?
> 
> Yes, im trying with your latest commit, running packaged executable using this [command](https://electron-react-boilerplate.js.org/docs/packaging#debugging-production-builds)
> 
> <img alt="image" width="1348" src="https://user-images.githubusercontent.com/32386713/271848915-a5ae3d4d-98d9-4763-a17f-affa35556cf0.png">

Oh, try without the `DEBUG_PROD` env. If you [enable this you will look for the database in the env path](https://github.com/tuliocll/electron-react-sqlite-todo/blob/feat/offline-auth/src/main/services/Database.service.ts#L11).
I use this to build:
```
npx cross-env CSC_IDENTITY_AUTO_DISCOVERY=false npm run package --mac
```

The `CSC_IDENTITY_AUTO_DISCOVERY` env is to disable the code signing and the `--mac` to build only for mac.

**Comment by anserwaseem** [comment]
Tried this command, still facing issue
> I still get that popup "Error registering user" with false being logged in console,
Additionally, when I try to log in, it throws this error (tried packaging the app on Mac M2 Max and Windows 11; seeing same issues on both systems)

I think app is being packaged right but there is some other issue !! 
Do I need to run some other command or chores before packaging?

**Comment by tuliocll** [comment]
No, i just run this `npx cross-env CSC_IDENTITY_AUTO_DISCOVERY=false npm run package --mac` and open:
https://github.com/tuliocll/electron-react-sqlite-todo/assets/22357579/fa104b17-9a97-4ccd-a87b-61c9e876bd97

Maybe cache? Try to delete the `release/build` folder (don't delete the `release/app`) and run again.

**Comment by anserwaseem** [comment]
> No, i just run this `npx cross-env CSC_IDENTITY_AUTO_DISCOVERY=false npm run package --mac` and open: https://github.com/tuliocll/electron-react-sqlite-todo/assets/22357579/fa104b17-9a97-4ccd-a87b-61c9e876bd97
> 
> Maybe cache? Try to delete the `release/build` folder (don't delete the `release/app`) and run again.

Yes, deleting `release/build` folder and running `npx cross-env CSC_IDENTITY_AUTO_DISCOVERY=false npm run package --Mac` worked like a charm!

Thank you so much @tuliocll ❤️

**Comment by tuliocll** [comment]
I'm glad I could help.
