### ISSUE TITLE
A blank white screen appears after logging out in packaged app

### ISSUE THREAD

**Issue by anserwaseem** [tuliocll/electron-react-sqlite-todo#4]
When logout link is pressed, `login` screen is shown for a some micro seconds, then a blank white screen appears.
This behaviour is only in packaged app!

Kindly open the video to see
https://github.com/tuliocll/electron-react-sqlite-todo/assets/32386713/5ff90a9d-6b5b-4ad5-a641-a98a9054a3b7

**Comment by tuliocll** [comment]
I can't test right now but try to remove this line https://github.com/tuliocll/electron-react-sqlite-todo/blob/feat/offline-auth/src/renderer/providers/Auth.tsx#L24 and test again.

**Comment by anserwaseem** [comment]
> I can't test right now but try to remove this line https://github.com/tuliocll/electron-react-sqlite-todo/blob/feat/offline-auth/src/renderer/providers/Auth.tsx#L24 and test again.

[Fixed](https://github.com/tuliocll/electron-react-sqlite-todo/pull/5), thank you @tuliocll ❤️
